### PR TITLE
Created gitignore with Python customisation.

### LINKED ISSUE #4: Improve gitignore for Python
Add most common Python extensions/dirs to `.gitignore`.

### PR DESCRIPTION
**Pull request by rtaib**
Added Python gitignores from: <https://raw.githubusercontent.com/github/gitignore/main/Python.gitignore>

Fixes #4.
Please delete branch after merge.

### CODE REVIEW

**Comment by mpaget** [comment]
Heaps more than necessary .. but not a blocker (can refine later if we wish).

**Comment by rtaib** [comment]
I will use the easi gitignore Matt suggested.

**Comment by rtaib** [comment]
Added an in-between version of `.gitignore` which should cover the basic Python needs. Ready to merge.

**Review by eric542 — APPROVED** [review]
Looks good

**Pull request merged**
